name: Generate RSS

on:
  push:
    paths:
      - 'data/**/*.json'   # trigger saat JSON diubah

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate RSS
        run: node generate-rss.js

      - name: Commit and Push RSS
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add rss.xml
          git commit -m "Update RSS automatically" || echo "No changes"
          git push
